Repository openviess/PyViCare, pull requests merged in 2024-09, with the labels that each got.

#382 fix(pylint): correct method description
  PyViCare/PyViCareHeatPump.py
Labels: maintenance

#378 chore(release): add Release Drafter workflow
  .github/release-drafter.yml
  .github/workflows/draft-release.yml
  .github/workflows/release.yml
Labels: ci

#380 fix: correct unit getter for heating.gas.consumption.summary.dhw
  PyViCare/PyViCareGazBoiler.py
  tests/test_Vitodens100W.py
Labels: bugfix

#394 chore(ci): remove eol python version
  .github/workflows/build.yml
Labels: ci

#395 chore(ci): test with recent python versions
  .github/workflows/build.yml
Labels: ci

#381 feat(deprecation): remove usage of deprecated data points
  PyViCare/PyViCareHeatPump.py
  PyViCare/PyViCareHeatingDevice.py
  PyViCare/PyViCareVentilationDevice.py
  tests/test_TestForMissingProperties.py
  tests/test_VitoairFs300E.py
  tests/test_Vitocal250A.py
  tests/test_Vitocaldens222F.py
  tests/test_VitolaUniferral.py
Labels: enhancement

#391 chore(ci): add Codespell workflow
  .github/workflows/lint.yml
  PyViCare/Feature.py
  README.md
  poetry.lock
  pyproject.toml
Labels: maintenance

#400 chore(ci): add pylint workflow
  .github/workflows/lint.yml
  .pylintrc
  poetry.lock
  pyproject.toml
Labels: ci

#401 chore(ci): add mypy workflow
  .github/workflows/type.yml
  PyViCare/PyViCareAbstractOAuthManager.py
  poetry.lock
  pyproject.toml
Labels: ci

#405 chore(testdata): Add Vitodens 050W data
  tests/response/Vitodens050W.json
  tests/test_TestForMissingProperties.py
Labels: documentation

#389 chore(testdata): Update Vitoair Fs300E data
  tests/response/VitoairFs300E.json
  tests/test_TestForMissingProperties.py
  tests/test_VitoairFs300E.py
Labels: documentation

#345 chore(testdata): Add Vitocal 333-G data
  tests/response/Vitocal333G.json
  tests/test_TestForMissingProperties.py
Labels: documentation

#324 chore(testdata): Add Vitocal 151A data
  tests/response/Vitocal151A.json
  tests/test_TestForMissingProperties.py
Labels: documentation

#295 chore(testdata): Add Vitodens 343F data
  tests/response/Vitodens343F_B3UF.json
Labels: documentation

#292 chore(testdata): Add Vitodens 100W data
  tests/response/Vitodens100W_B1HC-26.json
Labels: documentation

#397 chore(testdata): Update Vitocal 250A data
  tests/response/Vitocal250A.json
  tests/test_TestForMissingProperties.py
  tests/test_Vitocal250A.py
Labels: documentation

#371 feat: Add methods for heat pump cooling consumption
  PyViCare/PyViCareHeatPump.py
  tests/test_TestForMissingProperties.py
  tests/test_Vitocal151A.py
Labels: new-feature

#407 chore(testdata): Add Vitocal 252 data
  tests/response/Vitocal252.json
Labels: documentation

#370 chore(testdata): Add Vitocal 111S data
  tests/response/Vitocal111S.json
  tests/response/VitoconnectOpto2.json
  tests/test_TestForMissingProperties.py
Labels: documentation

#411 fix: make types-requests only a dev dependency
  poetry.lock
  pyproject.toml
Labels: bugfix
